# Generated by Django 5.1.3 on 2024-12-02 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('option1', models.CharField(max_length=255, verbose_name='Variant 1')),
                ('option2', models.CharField(max_length=255, verbose_name='Variant 2')),
                ('option3', models.CharField(max_length=255, verbose_name='Variant 3')),
                ('option4', models.CharField(max_length=255, verbose_name='Variant 4')),
                ('correct_option', models.IntegerField(verbose_name="To'g'ri javob (1-4)")),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Quiz nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('deadline', models.DateTimeField(verbose_name='Oxirgi muddat')),
                ('max_attempts', models.IntegerField(default=1, verbose_name='Maksimal urinishlar')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.IntegerField(verbose_name='Tanlangan javob')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri yoki noto'g'ri")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student', verbose_name='Talaba')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.question', verbose_name='Savol')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz_app.quiz', verbose_name='Quiz'),
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0, verbose_name='Natija')),
                ('attempt_date', models.DateTimeField(auto_now_add=True, verbose_name='Urinish sanasi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student', verbose_name='Talaba')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quiz', verbose_name='Quiz')),
            ],
        ),
    ]
