# Generated by Django 5.1.3 on 2024-12-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='points_per_question',
            field=models.FloatField(default=1.0, verbose_name='Har bir savol uchun ball'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_count',
            field=models.IntegerField(default=5, verbose_name='Savollar soni'),
        ),
    ]
