# Generated by Django 5.1.3 on 2024-12-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_quiz_points_per_question_quiz_question_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name_plural': 'Javoblar'},
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={'verbose_name_plural': 'Natijalar'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Testlar boshqaruvi'},
        ),
    ]
