# Generated by Django 5.1.3 on 2024-12-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_alter_answer_options_alter_attempt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Javob', 'verbose_name_plural': 'Javoblar'},
        ),
        migrations.AlterModelOptions(
            name='attempt',
            options={'verbose_name': 'Natija', 'verbose_name_plural': 'Natijalar'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Testlar boshqaruvi'},
        ),
    ]
